
# # Because I'm using ansible_connection = local, so I have to remove docker first because of the conflict of the docker version on local.
# - name: Remove docker
#   shell: 
#     cmd: snap remove docker

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Download Docker GPG key and save to keyring
  become: true
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    warn: false

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: false

- name: Start Docker service
  service:
    name: docker 
    state: started

- name: Check the docker version
  shell:
    cmd: docker --version

- name: Install Python 3 and pip
  raw: apt-get update && apt-get install -y python3 python3-pip
  
- name: Upgrade urllib3 and requests
  pip:
    name:
      - urllib3
      - requests
    state: latest


- name: Install Docker Engine & Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
