version: '3.8'

services:
  flask-app:
    container_name: flask-app
    image: khanhquocphamdev/flask-sum-api:2.2
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"